### ISSUE TITLE
O que falta pro Open Source?

### ISSUE THREAD

**Issue by angeliski** [ResultadosDigitais/hellper#1]
O Hellper sem dúvidas é uma ferramenta fantástica e nos ajuda (e muito) no pior dos momentos: incidentes.

A ideia aqui é discutir o que falta (Features/ Acomplamento com a RD/Documentação/ Outros) para disponibilizamos essa ferramenta como open source. 

Um bom exemplo de uma ferramenta é o [Dispatch](https://hawkins.gitbook.io/dispatch/) da Netflix.
O resultado dessa issue é um Roadmap pra a nossa V1 Open Source

**Comment by kaiofelipejs** [comment]
@GLOFonseca podemos fechar aqui?

**Comment by GLOFonseca** [comment]
Bem lembrado @kaiofelipejs
