### ISSUE TITLE
/hellper_status mention the user group when the pinned message has a mention of this kind

### ISSUE THREAD

**Issue by GLOFonseca** [ResultadosDigitais/hellper#126]
### Subject of the issue

/hellper_status mention the user group when the pinned message has a mention of this kind

### Steps to reproduce

1. Send a message mentioning a user group on it
2. Pin this message
3. Call the Hellper command `/hellper_status`

### Expected behavior

The Hellper should print the message, but without the mention.

### Actual behavior

The Hellper mentions the group again in the channel.

**Comment by yurighensev** [comment]
Working on it!
