### ISSUE TITLE
The bot owner is the user who is archiving the channel

### ISSUE THREAD

**Issue by biancamouta** [ResultadosDigitais/hellper#13]
### Subject of the issue
The owner of the bot, the one who reinstalled it, is the one that is archiving the incident channel in Slack.

![image](https://user-images.githubusercontent.com/56843536/71122081-89f10b80-21be-11ea-9d47-0d43707acd7d.png)

### Steps to reproduce

Using the command `/hellper_close` in any incident.

### Expected behaviour

We have two options, that should be discussed:

- The bot user archives the channel
OR
- The user that called the close command archives the channel

### Actual behaviour

The owner of the bot is archiving the channel.

### Possible Solution

We need to revise the scopes of our Oauth in the Slack App, one of them should permit the bot to archive a channel as itself, or as the user that called him.

**Comment by tiagotor** [comment]
Fixed by using OAuth Token.
