### ISSUE TITLE
Remove JoinConversation call

### ISSUE THREAD

**Issue by GLOFonseca** [ResultadosDigitais/hellper#139]
When an incident is opened we call the `slack-go.JoinConversation`, but this is no longer necessary.

### Cleanup

**What should be cleaned up or changed**:
Remove JoinConversation call on open_incident command (internal/commands/open.go)

**Provide any links for context**:
![image](https://user-images.githubusercontent.com/18470453/94446293-d1a9b800-017e-11eb-92bf-150294b8611e.png)

**Comment by carantunes** [comment]
Can I do this one?
