### ISSUE TITLE
The bot owner is the user who is opening the channel

### ISSUE THREAD

**Issue by biancamouta** [ResultadosDigitais/hellper#14]
### Subject of the issue
The owner of the bot, the one who reinstalled it, is the one that is opening the incident channel in Slack.

### Steps to reproduce

Using the command `/hellper_incident` in any incident.

### Expected behaviour

We have two options, that should be discussed:

- The bot user opens the channel
OR
- The user that called the close command opens the channel

### Actual behaviour

The owner of the bot is opening the channel.

### Possible Solution

We need to revise the scopes of our Oauth in the Slack App, one of them should permit the bot to open a channel as itself or as the user that called him.

**Comment by tiagotor** [comment]
Fixed by using OAuth Token.
