### ISSUE TITLE
Only the owner of the bot is able to receive the return of private messages

### ISSUE THREAD

**Issue by danielleqa** [ResultadosDigitais/hellper#23]
### Subject of the issue

We identified that when trying to send the command privately to the bot with a user other than the owner of the bot, the same can not reply on the channel saying that it does not exist.

This problem occurs because of the oauth token used in the operation. A bot in the slack has 2 types of oauth token and all are needed for the correct operation of the bot. We need to identify the correct mechanism for using these tokens.

**Comment by tiagotor** [comment]
this scenario doesn't happens anymore.
