### ISSUE TITLE
Create more alerts for Slack

### ISSUE THREAD

**Issue by tiagoemsi** [ResultadosDigitais/hellper#7]
### Feature Description

The Hellper Bot could have more alerts, to ensure the date's filling, incident's closening, postmortem, etc... If needed, it could even send a @ channel.

### Problem

Some incidents were not closed properly, had missing dates values or had the postmortem done many days after the incident occurred.

### Expected behaviour

We need a way to remind the incident commander to fill in the incident's dates, close the incident and also do the postmortem as soon as possible.

**Comment by GLOFonseca** [comment]
@tiagoemsi this was resolved, right?
